//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LsysParser.Data.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Error
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public int ErrorSourceId { get; set; }
        public Nullable<int> Code { get; set; }
        public string Message { get; set; }
    }
}
