//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LsysParser.Data.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Property
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int NameId { get; set; }
        public int ValueId { get; set; }

        public virtual Product product { get; set; }
        public virtual PropertyName NameObj { get; set; }
        public virtual PropertyValue ValueObj { get; set; }
    }
}
